### ISSUE TITLE
Surface.LiveComponent - Raise (BadMapError) expected a map, got: nil if a component defined update/2 callback 

### ISSUE THREAD

**Issue by technicalcapt** [msaraiva/surface#21]
Hi @msaraiva ,  I updated the latest commit from master and got the following error.
`** (BadMapError) expected a map, got: nil`

Just tried it in `data_component_test.exs`
```elixir
  defmodule StatefulComponent do
    use Surface.LiveComponent

    def update(assigns, socket) do
      {:ok, assign(socket, test: "test")}
    end

    def render(assigns) do
      ~H"""
      <div>Stateful</div>
      """
    end
  end
```
and running the test will output
```elixir
** (BadMapError) expected a map, got: nil
     code: {:ok, _view, html} = live_isolated(build_conn(), ViewWithNoBindings)
     stacktrace:
       (elixir) lib/map.ex:744: Map.split(nil, [:__default__])
       (surface) lib/surface/content_handler.ex:21: Surface.ContentHandler.init_contents/1
```

**Comment by msaraiva** [comment]
@technicalcapt fixed on master! Thanks a lot for reporting the issue.
