### ISSUE TITLE
Combining `:if` and `:props` on a slot raises an error

### ISSUE THREAD

**Issue by zachdaniel** [msaraiva/surface#224]
Big stack trace dump:
```
== Compilation error in file lib/ash_phoenix/components/data_table2.ex ==
** (FunctionClauseError) no function clause matching in Surface.Directive.SlotProps.process/2

    The following arguments were given to Surface.Directive.SlotProps.process/2:

        # 1
        %Surface.AST.Directive{meta: #Surface.AST.Meta<checks: [no_undefined_assigns: true], file: "/Users/zachdaniel/dev/ash/ash_phoenix/lib/ash_phoenix/components/data_table2.ex", line: 44, module: nil, node_alias: nil, ...>, module: Surface.Directive.SlotProps, name: :props, value: %Surface.AST.AttributeExpr{meta: #Surface.AST.Meta<checks: [no_undefined_assigns: true], file: "/Users/zachdaniel/dev/ash/ash_phoenix/lib/ash_phoenix/components/data_table2.ex", line: 44, module: nil, node_alias: nil, ...>, original: "foo: 1", value: [foo: 1]}}

        # 2
        %Surface.AST.If{children: [%Surface.AST.Slot{default: [%Surface.AST.Literal{value: "\n    "}, %Surface.AST.Tag{attributes: [], children: [%Surface.AST.Literal{value: "Loading..."}], debug: [], directives: [], element: "span", meta: #Surface.AST.Meta<checks: [no_undefined_assigns: true], file: "/Users/zachdaniel/dev/ash/ash_phoenix/lib/ash_phoenix/components/data_table2.ex", line: 45, module: nil, node_alias: nil, ...>}, %Surface.AST.Literal{value: "\n  "}], directives: [%Surface.AST.Directive{meta: #Surface.AST.Meta<checks: [no_undefined_assigns: true], file: "/Users/zachdaniel/dev/ash/ash_phoenix/lib/ash_phoenix/components/data_table2.ex", line: 44, module: nil, node_alias: nil, ...>, module: Surface.Directive.If, name: :if, value: %Surface.AST.AttributeExpr{meta: #Surface.AST.Meta<checks: [no_undefined_assigns: true], file: "/Users/zachdaniel/dev/ash/ash_phoenix/lib/ash_phoenix/components/data_table2.ex", line: 44, module: nil, node_alias: nil, ...>, original: " @loading ", value: {{:., [generated: true], [{:__aliases__, [generated: true, alias: false], [:Surface, :TypeHandler]}, :expr_to_value!]}, [generated: true], [:boolean, ":if", [{:@, [line: 44], [{:loading, [line: 44], nil}]}], [], nil, " @loading "]}}}, %Surface.AST.Directive{meta: #Surface.AST.Meta<checks: [no_undefined_assigns: true], file: "/Users/zachdaniel/dev/ash/ash_phoenix/lib/ash_phoenix/components/data_table2.ex", line: 44, module: nil, node_alias: nil, ...>, module: Surface.Directive.SlotProps, name: :props, value: %Surface.AST.AttributeExpr{meta: #Surface.AST.Meta<checks: [no_undefined_assigns: true], file: "/Users/zachdaniel/dev/ash/ash_phoenix/lib/ash_phoenix/components/data_table2.ex", line: 44, module: nil, node_alias: nil, ...>, original: "foo: 1", value: [foo: 1]}}], index: %Surface.AST.Literal{value: 0}, meta: #Surface.AST.Meta<checks: [no_undefined_assigns: true], file: "/Users/zachdaniel/dev/ash/ash_phoenix/lib/ash_phoenix/components/data_table2.ex", line: 44, module: nil, node_alias: nil, ...>, name: :loader, props: []}], condition: %Surface.AST.AttributeExpr{meta: #Surface.AST.Meta<checks: [no_undefined_assigns: true], file: "/Users/zachdaniel/dev/ash/ash_phoenix/lib/ash_phoenix/components/data_table2.ex", line: 44, module: nil, node_alias: nil, ...>, original: " @loading ", value: {{:., [generated: true], [{:__aliases__, [generated: true, alias: false], [:Surface, :TypeHandler]}, :expr_to_value!]}, [generated: true], [:boolean, ":if", [{:@, [line: 44], [{:loading, [line: 44], nil}]}], [], nil, " @loading "]}}, debug: [], meta: #Surface.AST.Meta<checks: [no_undefined_assigns: true], file: "/Users/zachdaniel/dev/ash/ash_phoenix/lib/ash_phoenix/components/data_table2.ex", line: 44, module: nil, node_alias: nil, ...>}

    Attempted function clauses (showing 1 out of 1):

        def process(directive, %Surface.AST.Slot{} = slot)

    lib/surface/directive/slot_props.ex:15: Surface.Directive.SlotProps.process/2
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/surface/compiler.ex:171: anonymous fn/3 in Surface.Compiler.to_ast/2
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/surface/compiler.ex:168: Surface.Compiler.to_ast/2
    lib/surface/compiler.ex:275: Surface.Compiler.convert_node_to_ast/3
    lib/surface/compiler.ex:169: anonymous fn/3 in Surface.Compiler.to_ast/2
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/surface/compiler.ex:168: Surface.Compiler.to_ast/2
    lib/surface/compiler.ex:111: Surface.Compiler.compile/5
    expanding macro: Surface.sigil_H/2
    lib/ash_phoenix/components/data_table2.ex:40: AshPhoenix.Components.DataTable2.render/1
    (elixir 1.10.4) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Here is a gist of the full component: https://gist.github.com/zachdaniel/0df35369443e78b54a4cb003c8dce955

Its pretty hacked together at the moment :D 

The issue arises when I try to add an `:if` to a `<slot>` that also has `:props`. I've been able to reproduce this in other live components. I think, for now, I can just wrap it in something else that has the `:if`, though, so not a big deal for me.

**Comment by msaraiva** [comment]
Fixed in https://github.com/msaraiva/surface/commit/bc9957a173899e695063eacc76f7b46db854b29e.

@zachdaniel thanks for the detailed report! ❤️
