### ISSUE TITLE
UnicodeConversionError in Surface compiler

### ISSUE THREAD

**Issue by hok** [msaraiva/surface#241]
Issue #90, which is already fixed, reports a problem with special characters used in expressions. 

I ran into a similar problem and am not sure how this case is different. The problem can be reproduced by using the same input as in #90 in the `compiler_test.exs` file:

**Test to reproduce the problem**

```elixir
  test "component with expression using special characters in the parameter" do
    code = """
    <h2 class="text-2xl">{{ "héllo" }}</h2>
    """

    [node | _] = Surface.Compiler.compile(code, 1, __ENV__)
  end
```

**Error**

```
** (UnicodeConversionError) invalid encoding starting at <<233, 108, 108, 111, 34, 32>>
     code: [node | _] = Surface.Compiler.compile(code, 1, __ENV__)
     stacktrace:
       (elixir 1.11.2) lib/string.ex:2299: String.to_charlist/1
       (elixir 1.11.2) lib/code.ex:838: Code.string_to_quoted/2
       (surface 0.1.1) lib/surface/compiler/helpers.ex:30: Surface.Compiler.Helpers.interpolation_to_quoted!/2
       (surface 0.1.1) lib/surface/compiler.ex:210: Surface.Compiler.convert_node_to_ast/3
       (surface 0.1.1) lib/surface/compiler.ex:169: anonymous fn/3 in Surface.Compiler.to_ast/2
       (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
       (surface 0.1.1) lib/surface/compiler.ex:168: Surface.Compiler.to_ast/2
       (surface 0.1.1) lib/surface/compiler.ex:275: Surface.Compiler.convert_node_to_ast/3
       (surface 0.1.1) lib/surface/compiler.ex:169: anonymous fn/3 in Surface.Compiler.to_ast/2
       (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
       (surface 0.1.1) lib/surface/compiler.ex:168: Surface.Compiler.to_ast/2
       (surface 0.1.1) lib/surface/compiler.ex:111: Surface.Compiler.compile/5
       test/compiler_test.exs:94: (test)
```

**Comment by msaraiva** [comment]
Fixed in https://github.com/msaraiva/surface/commit/24da80b5dbd2225987fe95a44ebd1cb7fc19abe2.

@hok thanks for the report and the provided test! ❤️
