### ISSUE TITLE
Template parsing issue with handlebars in a string

### ISSUE THREAD

**Issue by brainlid** [msaraiva/surface#34]
This may be an odd edge case. But check this out...

```elixir
~H"""
<div style="height: {{ @dragging_height }}px;">
</div>
"""
```

This results the following compilation error.

```
== Compilation error in file lib/fe_web/views/editor/item.ex ==
** (TokenMissingError) lib/fe_web/views/editor/item.ex:74: missing terminator: " (for string starting at line 74)
    (eex 1.10.1) lib/eex/compiler.ex:45: EEx.Compiler.generate_buffer/4
    expanding macro: Surface.sigil_H/2
    lib/fe_web/views/editor/item.ex:73: FeWeb.Editor.Item.render/1
    (elixir 1.10.1) expanding macro: Kernel.if/2
    lib/fe_web/views/editor/item.ex:72: FeWeb.Editor.Item.render/1
```

Rewriting it this way fixed the issue.

```elixir
style_text = "height: #{assigns.dragging_height}px;"
~H"""
<div style={{style_text}}>
</div>
"""
```

The issue appears to be when putting `{{ @stuff }}` inside a string it confuses the parser.

**Comment by msaraiva** [comment]
Fixed in https://github.com/msaraiva/surface/commit/170796626993ef98d973ebf7faa6280dce755d36

@brainlid thanks for reporting this.
