### ISSUE TITLE
UnicodeConversionError when using special character in expression

### ISSUE THREAD

**Issue by MrYawe** [msaraiva/surface#90]
I got another `UnicodeConversionError` when using special character in expression as a value of an attribute.

I tried to replace `IO.iodata_to_binary()` by `IO.chardata_to_string()` in `tag_translator.ex` line `176` like I've done in https://github.com/msaraiva/surface/pull/78/files but I got another exception.

I may take a deeper looker later but, in the meantime, here is the issue.

**How to reproduce**
```elixir
test "with utf-8 expression attribute value" do
      assigns = %{}

      code = ~H"""
      <div title={{ "héllo" }}/>
      """

      assert render_static(code) =~ """
             <div title="héllo"></div>
             """
end
```
**Error**
```
== Compilation error in file test/html_tag_test.exs ==
** (UnicodeConversionError) invalid encoding starting at <<233, 108, 108, 111, 34>>
    (elixir 1.10.2) lib/list.ex:944: List.to_string/1
    (surface 0.1.0-alpha.2) expanding macro: Surface.sigil_H/2
    test/html_tag_test.exs:83: HtmlTagTest."test basic attibutes with utf-8 expression attribute value"/1
    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:396: Kernel.ParallelCompiler.require_file/2
    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:306: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by msaraiva** [comment]
Fix in 0b649770f0440475470a3c5dc393debfb4d9efb4.

@MrYawe thanks for the detailed report.
